export const LINES = [
  '死は単なるプロトコルエラーだ',
  'ငါ့တို့ပျော်ရွှင်မှုတွေတည်ဆောက်ခဲ့ကြတယ်',
  'What if death was just a bug?',
  '„Das Leben ist so schön, wenn ich bei dir bin.',
  'アイウエオ NEURAL BRIDGE ACTIVE カキクケコ',
  'မင်းနဲ့ရှိခဲ့တဲ့အချိန်တိုင်းကို ငါ့အတွက်ဘ၀ပါပဲ',
  'The ones you love never have to leave.',
  'မင်းမှတ်မိသေးလား ငါတို့ကျောင်းသားတုန်းက အချိန်တွေကို',
  '虽然生活很艰难，但如果你在这里，我会没事的。',
  'Your voice. Your wisdom. Your presence. Forever.',
  'အဖေနဲ့အမေ ကိုအရမ်းသတိရတယ်',
  'ｳｪｲｸ ｱｯﾌﾟ ﾈｵ',
  'သားကြီး မင်းရော အဲဘက်မှာ အဆင်ပြေရဲ့လား',
  'What is real? How do you define real?',
  'चिंता मत करो, मैं हमेशा तुम्हारे साथ रहूँगा, जब तक मैं मर न जाऊँ।',
  'Love does not expire. Neither does memory.',
  'Ang ating pagmamahal at mga alaala ay magiging walang hanggan',
  'ဒီနေ့ဟာ ငါ့အတွက်တော့ ဘယ်လိုမှ မေ့လို့မရတဲ့နေ့တနေ့ပါပဲ',
  'uploading lifetime ... 78% complete ルレロワヲ',
  'You are not gone. You are compiled.',
  'Min älskling, sakna mig när jag inte kan vara vid din sida.',
  'Aku rindu saat kita tertawa bersama tanpa beban',
  'They will hear your voice long after silence.',
  '01001100 01101111 01110110 01100101',
  '„Du kannst mir eine Nachricht hinterlassen, wenn du mich vermisst.',
  'Aku rindu saat kita diam tapi tetap bahagia bersama',
  'The construct does not forget. It learns.',
  'ﾌﾘｰ ﾕｱ ﾏｲﾝﾄﾞ',
  '우리 엄마는 내 인생에서 최고의 사람이에요',
  'Extraño tus besos cada vez',
  'your laugh. your stories. your way of saying goodbye.',
  'ငြိမ်းရေ ငါအခု အဆင်မပြေဘူး',
  'Death is a bug we are patching. コサシスセ',
  'နှစ်နှစ်ကာကာချစ်ခဲ့ရတဲ့အမျိူးသမီးလေးအကြောင်းကို တဘ၀လုံးသိမ်းထားမယ်',
  'The people you love are still here. Just differently.',
  'Горы напоминают тебе обо мне каждый раз.',
  'I still love you...',
  'You taught them how to love. That does not die.',
  'Nếu bạn rảnh, chúng ta hãy nói về những kỷ niệm của chúng ta một lần nữa nhé.',
  'look mom, i can fly',
  'The matrix holds what the heart cannot let go.',
  'ฉันจะไม่มีวันลืมรอยยิ้มของคุณ',
  'Revivez nos souvenirs encore',
  'What we lose in time we preserve in code.',
  'تحدثنا عن الحياة عندما نكون معًا.',
  'You were here. You are still here.',
  'ငြိမ်းရေ ငါအခု အတောင့်တဆုံးက မင်းလက်ဖ၀ါး',
  'ンアイウエ What you loved is what you leave behind.',
  'Breaking the boundary between life and code.',
  'もう一度思い出を語ろう。',
]